### ISSUE TITLE
cant access req.body inside metadata.

### ISSUE THREAD

**Issue by rahil471** [devconcept/multer-gridfs-storage#1]
Hi, req.body is undefined inside the metadata function. 

```
metadata: function(req, file, cb) {
        let parsedMime = contentType.parse(file.mimetype);
        let meta = {};
        console.log(req.body); //undefined
}
```

But I can access it inside the upload function.

```
router.post('/upload', function(req, res){
    let mongoId = new mongoose.Types.ObjectId();
    req.mongoId = mongoId;
    uploadsingle(req, res, (err)=>{
      console.log(req.body);  //defined
      if(err){
        return utils.handleErrResp(req, res, err);
      }
      return res.json({
        responseCode: messages.defaultSuccessObject.responseCode,
        responseMessage: messages.defaultSuccessObject.responseMessage
      });
    });
});
```

**Comment by devconcept** [comment]
Hi. I tried to reproduce your bug without any success. The `req.body` object is available in all cases. I even use the source code you provided and it worked as expected.

The `req` object is received from `multer` and provided to your function without any modifications. The only reason why you get this parameter is in case you need  additional info of the request to help you decide which values  you will pass on the callback (naming, setting the storage collection, etc). In any other case this value is not used by this module.

As a side note you don't need to call the multer's upload function the way you are calling it to obtain the file identifier. You  can use the `req.file.id` property for this.

```
router.post('/upload', uploadsingle, function(req, res){
      console.log(req.file.id);  // the stored file id    
});
```
or in your case

```
uploadsingle(req, res, (err)=>{
      console.log(req.file.id);  // the stored file id 
});
```
If what you are doing is trying is to set the `id` of each file the `identifier` option can help you with that.

Please check your code because it is likely that you are passing the wrong object to the middleware function.
