### ISSUE TITLE
Deprecation warning when uploading files

### ISSUE THREAD

**Issue by DreiYan** [devconcept/multer-gridfs-storage#13]
(node:6411) DeprecationWarning: collection.insert is deprecated. Use insertOne, insertMany or bulkWrite instead. (Mongodb v3)

**Comment by devconcept** [comment]
Take a look [here](https://github.com/mongodb/node-mongodb-native/blob/da4df8941a06522571470a8f5448d0a86e49abc6/lib/gridfs-stream/upload.js#L280), [here](https://github.com/mongodb/node-mongodb-native/blob/da4df8941a06522571470a8f5448d0a86e49abc6/lib/gridfs-stream/upload.js#L433) and [here](https://github.com/mongodb/node-mongodb-native/blob/da4df8941a06522571470a8f5448d0a86e49abc6/lib/gridfs-stream/upload.js#L517). I think you should open a new issue in the mongo github repository. I'm sure they are aware of the problem because they started to use node deprecations on a recent version and that's why you are getting this warning.
