### ISSUE TITLE
req.body is empty in file callback, depending or request fields ordering 

### ISSUE THREAD

**Issue by hackash** [devconcept/multer-gridfs-storage#15]
#### I'm submitting a...

- [x] Bug report
- [ ] Feature request
- [ ] Documentation issue or request
- [ ] Support request
- [ ] Regression

#### Environment

- I'm using `multer-gridfs-storage` version *(^3.2.2)*

- My installed MongoDB version is *(v3.4.6)*

- I have Multer *(^1.3.1)* installed to upload files

- The Node version used to run the code is *(v10.1.0)*

#### Current behavior
`req.body` is empty in `file(req, file)` callback, when the multipart request contains texts fields after the file filed, but when the field comes before the file, it gets passed to the `req.body` 

#### Expected behavior
`req.body` should contain text fields, it does not matter whether the file comes before or after fields

**Comment by devconcept** [comment]
This is not a bug. It is in fact the expected behavior. See #7

Since this seems to be a recurrent issue here is a more elaborated answer:

 The `req.body` is not part of the node API, is just a property added to the request object by request parser modules like [`body-parser`](https://github.com/expressjs/body-parser/blob/56a2b73c26b2238bc3050ad90af9ab9c62f4eb97/lib/types/json.js#L105) or [`multer`](https://github.com/expressjs/multer/blob/19374b526a8032d2f34a74f274fba44601245937/lib/make-middleware.js#L28). It all boils down to the fact that in node the request **is a stream**.

You have to process the fields as they come because, unlike `json` or similar requests where the payload is small, multipart requests are potentially enormous. What do you do when you send a 50 Mb file and a small field at the end? Keep the file in memory just to read the field? Now imagine that with many files in a high traffic server. You'll run out of memory quickly.

Although you can technically [un-read a stream](https://nodejs.org/api/stream.html#stream_readable_unshift_chunk) in this case using it to peek fields ahead in the request is unpractical because it only creates more problems than it solves and you can bypass the problem altogether by placing the text fields at the beginning of your form or [FormData](https://developer.mozilla.org/en-US/docs/Web/API/FormData) object.

Ultimately remember that this module has a lot of cool features but is just a plugin. It has to consume the request streams as they are provided by `multer` which in turn receives them from [`busboy`](https://github.com/mscdex/busboy) as it parses the request. The `req` and `file` parameters are provided when `multer` invokes the [`_handleFile`](https://github.com/devconcept/multer-gridfs-storage/blob/2c31e731ac3e5d76bdd30ca9317bc2569a5f1833/lib/gridfs.js#L318) method.
