### ISSUE TITLE
Unable to prevent certain types of files from being saved in the DB using multer-gridfs-storage 

### ISSUE THREAD

**Issue by devivekw** [devconcept/multer-gridfs-storage#207]
*Please note, this may be a very dumb issue request. If you have seen a solution just link it below.*

### Unable to prevent certain types of files from being saved in the DB. 

**I am trying to only save images under the size of `5MB`**  
I am working on building an `express` API using NodeJS. I want to make sure that the client side of this app only submits photo's to the backend.   
But the issue I am facing is that [`file`](https://github.com/devconcept/multer-gridfs-storage#file) configuration function always saves a file to the database even if you pass an `undefined` or `null` object.

As you can see below. I was hoping to only save `images` but no matter what the input it always saves the file.
```js
const storage = new GridFsStorage({
    url: MONGO_URI,
    options: {
        useNewUrlParser: true,
        useUnifiedTopology: true
    },
    file: (req, file) => {
        if (file.contentType.includes('image/')) {
            return file;
        }
    }
});

const upload = multer({ storage });
```

I am not sure if this is the right approach for saving files using `multer-gridfs-storage` but this is the only one I could find.

**Environment**
I am using a Windows machine with WSL installed.
My Node Version -> `v12.18.1`
Package version -> `"multer-gridfs-storage": "^4.2.0"`

**Comment by devconcept** [comment]
Your request is unusual but is perfectly possible.

You have to create your own [Storage Engine](https://github.com/expressjs/multer/blob/master/StorageEngine.md) with the exact same options as this module and extend this exported storage class overriding the `_handleFile` method only. You will probably need an extra option to figure out which files to save. I advise against using the file option since is designed to provide file metadata only. You should use an extra option and have separate options with separate concerns. If the answer solved your problem or you need more assistance let me know to close the issue or provide additional info.
