### ISSUE TITLE
Transform file before save

### ISSUE THREAD

**Issue by Aeonrush** [devconcept/multer-gridfs-storage#5]
Hi
I'm planning to use this library (http://sharp.dimens.io/en/stable/) to provide file resize before saving into GridFS. It's possible with your library? I mean something like a transform function.
Thanks

**Comment by devconcept** [comment]
No, you can't, at least not in the way you are planning to do it. This is because you are not dealing with plain functions here but with streams. Node streams, once consumed, cannot be un-consumed; instead you create a new stream based on the old one. This library grabs the file streams from the request and pipes them to gridfs so the request streams are effectively consumed. 

The recommended approach here is that once you saved the files in GridFs you create a new stream per file using GridFsBucket (or GridStore on older versions) and pipe this new stream to the library in question. The `req.file` or `req.files` have sufficient information for this. I don't recommend you to process first and store later because, if you have an error processing, the file will be lost. This way you can retry the failed process because you already saved the file.

**Comment by Aeonrush** [comment]
Thanks for answering. I understood
