### ISSUE TITLE
Read file from storage

### ISSUE THREAD

**Issue by MarkSalabutin** [devconcept/multer-gridfs-storage#6]
How I can read file from storage?

**Comment by MarkSalabutin** [comment]
Okay, I'm finally done it using **"gridfs-stream" module**.
```javascript
let data = [];
let readStream = gfs.createReadStream({
  filename:  /*filename that you store in db*/
});
readStream.on('data', chunk => data.push(chunk));
readStream.on('end', () => {
  data = Buffer.concat(data);
  let img = `data:${file.mimetype};base64,${Buffer(data).toString('base64')}`;
  res.end(img) //or what you want to do with img
}
```
Leave this issue if you want, maybe it's solution will be useful for beginners like me.

**Comment by devconcept** [comment]
@MarkSalabutin  Sorry for the delayed answer. I don't recommend you to use `gridfs-stream` unless you are using `mongo < 2.2`. It uses [`GridStore`](http://mongodb.github.io/node-mongodb-native/2.1/api/GridStore.html) which is deprecated.

You should use the native [`GridFSBucket`](http://mongodb.github.io/node-mongodb-native/2.1/api/GridFSBucket.html) class that ships with mongo.

The only reason this library exists is because `GridStore` is awfull but `GridFSBucket` is a significant improvement as API to handle file streams.

**Comment by mebibou** [comment]
@devconcept how to retrieve the file using `gridFsBucket` ? I tried using `mongo-gridfs` like this:
```
const { MongoGridFS } = require('mongo-gridfs');
const { connect } = require('mongoose');

const connection = await mongoose.connect();
const gridFs = new MongoGridFS(connection.db, 'fs.chunks');
...
router.post('/', upload.single('doc'), (req, res) => {
  gridFs.findById(req.file.id).then(file => console.log(file));
});
```
but this just prints `null`
