### ISSUE TITLE
Uploading a png sets metadata to null. jpg and jpeg work most of the time

### ISSUE THREAD

**Issue by fromage9747** [devconcept/multer-gridfs-storage#7]
I have been making use of the metadata array in order to store user id's so that when I retrieve the files, I search by user id.

This works a treat for uploading jpeg and jpg, but in testing PNG, my metadata.user_id is set to null, each and every time.

Is there a known issue with PNGs?  The file is uploaded to the mongodb perfectly fine and I can see the document there, but the metadata.user_id is set to null.  I've done various troubleshooting and I am definitely sending and receiving the user_id when making the request, just the metadata is ignoring it.

**Comment by fromage9747** [comment]
Just an update on this.  Jpg occasionally doesn't work as well.  This is an intermittent problem. My code is exactly the same.  Some PNG's will work and include the UserID in the Metadata and then others will be undefined and turn up as null in the metadata. 

`const path = require('path');
const crypto = require('crypto');
const multer = require('multer');
const GridFsStorage = require('multer-gridfs-storage');
const config = require('./database');

// Create Storage object
const storage = new GridFsStorage({
    url: config.database,
    file: (req, file) => {
        return new Promise((resolve, reject) => {
            crypto.randomBytes(16, (err, buf) => {
                if (err) {
                    return reject(err);
                }
                const UserID = req.body.UserID;
                console.log('inside the promise:' + UserID);
                const filename = buf.toString('hex') + path.extname(file.originalname);
                const fileInfo = {
                    filename: filename,
                    metadata: {
                        user_id: UserID 
                    },
                    bucketName: 'uploads' 
                };
                resolve(fileInfo);
            });
        });
    }
});

const upload = module.exports = multer({ storage });`

**Comment by devconcept** [comment]
I think your problem is not related to this module but maybe to the client code that sends the user id. From the perspective of the mongodb server all the files are just binary data, there are no differences between them and the extension or format makes no difference when storing the file.

You said:

> If I try to access the req.body before the promise it is ALWAYS undefined

Sure it is. When you make a request to any server it must go through a body parser routine first before it can populate the body. In a regular Express app you usually use multer for parsing `FormData` requests and bodyparser for the other types. In this code `router.post('/upload', upload.single('userFile')`, the part `upload.single` is what kicks the parsing routine since is a multer middleware. After that in all the other middlewares the `body` is set and the data is available. Multer uses busboy and populates the body and files *as they arrive* so reading data that is probably still on the fly is probably another reason that could be causing the trouble. None of this is related to this module but the way multer and body parsing works.

**Comment by fromage9747** [comment]
@devconcept so in other words,  the metadata is something that is not reliable due to:

> Multer uses busboy and populates the body and files as they arrive so reading data that is probably still on the fly

 and should not be used?  

Anyway, no matter.  Thanks.  I'll refactor my code in the original way I was going to do it.

**Comment by devconcept** [comment]
> So in other words, the metadata is something that is not reliable

That's not exactly true. The metadata field **is reliable**, what is not reliable is trying to use the body while is been created. If you want to implement a search you should use regular database objects and perform the search on them. A simple reference to the file `id` will help you locate it after that. 

Remember that files are always bigger and harder to manipulate than database records (because you also need to do streaming too) therefore your solution should rely on data structures, not files.
