### ISSUE TITLE
status code: 500 when trying upload image to mongo

### ISSUE THREAD

**Issue by obiwankenoobi** [devconcept/multer-gridfs-storage#9]
I am using mongoose for connecting and my guess that Im not using the library correctly because of that , maybe you could assist with my issue. 

my connection looks like this: 
```
mongoose.connect('mongodb://foo123.mlab.com:12345/database', {
    auth: {
      user: 'username',
      password: 'password'
    }
  })
  .then(() => console.log('connection successful'))
  .catch((err) => console.error(err));
```

and my `multer-gridfs-storage` function looks like that:

```
const storage = require('multer-gridfs-storage')({
  url: 'mongodb://foo123.mlab.com:12345/database'
});


const upload = multer({storage: storage})

router.post('/', upload.single('carImage') ,(req, res) => {
    console.log('trying to upload image')
    console.log(req.file);    
    let todayArr = today.slice(0, 4);

})
```

Where am I wrong with my approach?

**Comment by obiwankenoobi** [comment]
fixed it with: 

```
const storage = require('multer-gridfs-storage')({
  url: 'mongodb://<username>:<passwowd>foo123.mlab.com:12345/database'
});
```
So what I thoughts is that there should be only one connection to my db as I establish using `mongoose.connect ` and I tried basically build the function based on that. But It works also by establish new connection inside the `storage` const. So my main connection is:

```
mongoose.connect('mongodb://foo123.mlab.com:12345/database', {
    auth: {
      user: 'username',
      password: 'password'
    }
  })
  .then(() => console.log('connection successful'))
  .catch((err) => console.error(err));
``` 

and to upload files inside the route Its: 
```
const storage = require('multer-gridfs-storage')({
  url: 'mongodb://<username>:<passwowd>foo123.mlab.com:12345/database'
});

const upload = multer({storage: storage})

router.post('/', upload.single('carImage') ,(req, res) => {
    console.log('trying to upload image')
    console.log(req.file);    
})
```

in case someone else struggle with it.

**Comment by devconcept** [comment]
May the force be with you, friend ;)

Since this seems to be a recurrent issue let´s take some time to address it.

This library has no relation with mongoose at all, neither in the dependencies nor in the way it works. This is mainly because mongoose is designed to store **data** while this library is designed to store **files**. The `Connection` object obtained after a successful connection to the database is an internal class of the mongoose library while we require a mongo-core `DB` object. This object is then used to create instances of `GridFSBucket` or `GridStore` streams (depending of your mongo version) and use those streams to properly store the files received in the request.

However, there is a way you can reuse the mongoose `Connection` with this library; you only have to access the property db of a given connection.

```javascript
mongoose.connect('mongodb://myurl:port/mydatabase').then(instance => {
    const db = instance.connection.db; // this is an actual mongo-core db
    const storage = require('multer-gridfs-storage')({
        db: db
    });
})
```

this also works

```javascript
const promisedDb = mongoose
    .connect('mongodb://myurl:port/mydatabase')
    .then(instance => instance.connection.db);
    
const storage = require('multer-gridfs-storage')({
    db: promisedDb
});
```

Mongoose can store several connections at once (opened with `createConnection`) and they are found in the `connections` property. The `connection` property is a shortcut of `connections[0]` and is the current active connection. You can get a db from any of those objects. This code is tested and it works. The property is also documented so is unlikely (but still possible) to be changed in the future.

**Comment by Atuldubey98** [comment]
**It Helped !**
